title: AJU studio | Bespoke Branding and Design
baseURL: https://ajustudio.co/
languageCode: en
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - term
markup:
  goldmark:
    renderer:
      unsafe: true
